### ISSUE TITLE
Chef-Solo CF template fails to create

### ISSUE THREAD

**Issue by slimandslam** [awslabs/aws-training-demo#2]
The following resource(s) failed to create: [AdminInstanceSecurityGroup, ChefEC2TrustAccessRole, ChefSoloBootstrappedSecurityGroup, AdminEC2TrustAccessRole, ArtifactS3Bucket]

**Comment by honux77** [comment]
I had same problem. Does anyone have a solution?

**Comment by kbiton** [comment]
Hello I am the demo creator can you please send me the full cloudformation output ? deploy  the CF stack with rollback disabled and capture the errors then kindly post them or send them directly to me I will troubleshoot.

**Comment by honux77** [comment]
Thanks for your support. 
I found that the reason I failed is the name of s3 bucket was duplicated. 
After I change the s3 bucket name, Stack creation succedded.

**Comment by sebsto** [comment]
closing as it appears to be fixed.
