### ISSUE TITLE
(ResourceNotFoundException) when calling the AddPermission operation: Function not found: arn:aws:lambda:us-east-2:715223779645:function:myTopic2017

### ISSUE THREAD

**Issue by ss1921** [awslabs/aws-training-demo#8]
When I try to hook S3 and Lambda together, I get the following error: 
`An error occurred (ResourceNotFoundException) when calling the AddPermission operation: Function not found: arn:aws:lambda:us-east-2:715223779645:function:myTopic2017`
Kindly help.

**Comment by AlFalahTaieb** [comment]
did you find a solution ?

**Comment by AlFalahTaieb** [comment]
@ss1921
